<a href="https://colab.research.google.com/github/Gopalchalak/Deep-Learning/blob/main/HyperParamterTunning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('sample_data/diabetes.csv')

In [8]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
df.isnull().sum()
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [10]:
x = df.iloc[:,:-1].values
y = df.iloc[:, -1].values

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
x = scaler.fit_transform(x)

In [14]:
x.shape

(768, 8)

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [16]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [17]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
model.fit(x_train, y_train, batch_size=32, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5000 - loss: 0.7088 - val_accuracy: 0.6104 - val_loss: 0.6623
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6319 - loss: 0.6480 - val_accuracy: 0.7208 - val_loss: 0.6113
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7182 - loss: 0.6018 - val_accuracy: 0.7597 - val_loss: 0.5743
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5693 - val_accuracy: 0.7922 - val_loss: 0.5468
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5434 - val_accuracy: 0.7922 - val_loss: 0.5269
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.5248 - val_accuracy: 0.7922 - val_loss: 0.5122
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5105 - val_accuracy: 0.7922 - val_loss: 0.5017
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4996 - val_accuracy: 0.7857 - val_loss: 0.4935
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4909 - val_accuracy: 0.7857 - val_loss: 0.4867
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4833 - val_accuracy: 0.7987 - val_loss: 0.4814
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4765 - val_accuracy: 0.7987 - val_loss: 0.4779
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4717 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4673 - val_accuracy: 0.7987 - val_loss: 0.4725
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4638 - val_accuracy: 0.7922 - val_loss: 0.4707
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4609 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4593 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4567 - val_accuracy: 0.7857 - val_loss: 0.4688
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4551 - val_accuracy: 0.7857 - val_loss: 0.4688
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4533 - val_accuracy: 0.7792 - val_loss: 0.4684
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4525 - val_accuracy: 0.7857 - val_loss: 0.4679
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4518 - val_accuracy: 0.7857 - val_loss: 0.4685
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4509 - val_accuracy: 0.7922 - val_loss: 0.4675
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4495 - val_accuracy: 0.7792 - val_loss: 0.4668
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4484 - val_accuracy: 0.7792 - val_loss: 0.4654
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4477 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4466 - val_accuracy: 0.7922 - val_loss: 0.4657
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4458 - val_accuracy: 0.7922 - val_loss: 0.4647
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4455 - val_accuracy: 0.7857 - val_loss: 0.4639
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4446 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4438 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4436 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4425 - val_accuracy: 0.7922 - val_loss: 0.4649
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4424 - val_accuracy: 0.7922 - val_loss: 0.4648
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4408 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4409 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4402 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4394 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4388 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4380 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4376 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4375 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4374 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4368 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4363 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4353 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4339 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4332 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4331 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4326 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4319 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4316 - val_accuracy: 0.7987 - val_loss: 0.4591
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4310 - val_accuracy: 0.7987 - val_loss: 0.4581
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4572
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4571
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4294 - val_accuracy: 0.7987 - val_loss: 0.4572
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4292 - val_accuracy: 0.7987 - val_loss: 0.4576
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4289 - val_accuracy: 0.7987 - val_loss: 0.4566
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4281 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4280 - val_accuracy: 0.8052 - val_loss: 0.4564
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4275 - val_accuracy: 0.8182 - val_loss: 0.4553
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4269 - val_accuracy: 0.8117 - val_loss: 0.4556
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4265 - val_accuracy: 0.8247 - val_loss: 0.4565
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4580
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4260 - val_accuracy: 0.8182 - val_loss: 0.4571
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4257 - val_accuracy: 0.8182 - val_loss: 0.4559
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.8182 - val_loss: 0.4564
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4249 - val_accuracy: 0.8182 - val_loss: 0.4563
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4552
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4250 - val_accuracy: 0.8182 - val_loss: 0.4554
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4244 - val_accuracy: 0.8182 - val_loss: 0.4551
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4237 - val_accuracy: 0.8182 - val_loss: 0.4550
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4235 - val_accuracy: 0.8182 - val_loss: 0.4553
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4230 - val_accuracy: 0.8182 - val_loss: 0.4554
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4232 - val_accuracy: 0.8117 - val_loss: 0.4541
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4224 - val_accuracy: 0.8182 - val_loss: 0.4541
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4224 - val_accuracy: 0.8182 - val_loss: 0.4525
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4217 - val_accuracy: 0.8182 - val_loss: 0.4533
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4212 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4214 - val_accuracy: 0.8182 - val_loss: 0.4536
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4209 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4210 - val_accuracy: 0.8117 - val_loss: 0.4540
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4208 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4206 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4199 - val_accuracy: 0.8117 - val_loss: 0.4530
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4199 - val_accuracy: 0.8182 - val_loss: 0.4525
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4197 - val_accuracy: 0.8182 - val_loss: 0.4514
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4195 - val_accuracy: 0.8247 - val_loss: 0.4522
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4189 - val_accuracy: 0.8182 - val_loss: 0.4521
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4190 - val_accuracy: 0.8052 - val_loss: 0.4519
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4188 - val_accuracy: 0.8182 - val_loss: 0.4519
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4181 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4178 - val_accuracy: 0.8117 - val_loss: 0.4515
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4178 - val_accuracy: 0.8052 - val_loss: 0.4514
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4172 - val_accuracy: 0.8117 - val_loss: 0.4514
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4167 - val_accuracy: 0.8117 - val_loss: 0.4511

In [19]:
#how to select approptiate aoptimizer
# no. of nodes in a layer
# how to select no. of layers
# all in all one model

In [20]:
pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [21]:
#how to select approptiate optimizer
import kerastuner as kt

/tmp/ipykernel_184/3321109293.py:2: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [22]:
def build_model1(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))
  optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [23]:
# from keras_tuner.src.engine import objective
tuner = kt.RandomSearch(build_model1, objective= 'val_accuracy', max_trials=5)

In [24]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 19s

In [25]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [26]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch= 6, validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7590 - loss: 0.5114 - val_accuracy: 0.7922 - val_loss: 0.4949
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4987 - val_accuracy: 0.7922 - val_loss: 0.4879
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4907 - val_accuracy: 0.7987 - val_loss: 0.4846
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4851 - val_accuracy: 0.7987 - val_loss: 0.4811
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7704 - loss: 0.4794 - val_accuracy: 0.8052 - val_loss: 0.4791
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4748 - val_accuracy: 0.8052 - val_loss: 0.4781
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7850 - loss: 0.4716 - val_accuracy: 0.8052 - val_loss: 0.4764
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7736 - loss: 0.4686 - val_accuracy: 0.8117 - val_loss: 0.4760
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7752 - loss: 0.4662 - val_accuracy: 0.8117 - val_loss: 0.4756
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7818 - loss: 0.4637 - val_accuracy: 0.8117 - val_loss: 0.4747
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7785 - loss: 0.4612 - val_accuracy: 0.8052 - val_loss: 0.4754
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7785 - loss: 0.4600 - val_accuracy: 0.7987 - val_loss: 0.4758
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7785 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4751
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7785 - loss: 0.4566 - val_accuracy: 0.8117 - val_loss: 0.4744
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7818 - loss: 0.4551 - val_accuracy: 0.8117 - val_loss: 0.4741
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.4544 - val_accuracy: 0.8182 - val_loss: 0.4743
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7785 - loss: 0.4527 - val_accuracy: 0.8182 - val_loss: 0.4739
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4519 - val_accuracy: 0.8182 - val_loss: 0.4736
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7818 - loss: 0.4508 - val_accuracy: 0.8182 - val_loss: 0.4722
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7850 - loss: 0.4500 - val_accuracy: 0.8182 - val_loss: 0.4728
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4490 - val_accuracy: 0.8182 - val_loss: 0.4717
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4484 - val_accuracy: 0.8182 - val_loss: 0.4706
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4477 - val_accuracy: 0.8117 - val_loss: 0.4702
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7883 - loss: 0.4470 - val_accuracy: 0.8117 - val_loss: 0.4699
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4461 - val_accuracy: 0.8117 - val_loss: 0.4691
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4454 - val_accuracy: 0.8052 - val_loss: 0.4705
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7801 - loss: 0.4449 - val_accuracy: 0.8052 - val_loss: 0.4701
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4444 - val_accuracy: 0.8117 - val_loss: 0.4694
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4435 - val_accuracy: 0.8182 - val_loss: 0.4684
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4429 - val_accuracy: 0.8182 - val_loss: 0.4687
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4426 - val_accuracy: 0.8052 - val_loss: 0.4688
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7818 - loss: 0.4418 - val_accuracy: 0.8182 - val_loss: 0.4674
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4411 - val_accuracy: 0.8182 - val_loss: 0.4668
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4413 - val_accuracy: 0.8247 - val_loss: 0.4664
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4402 - val_accuracy: 0.8117 - val_loss: 0.4660
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4401 - val_accuracy: 0.8182 - val_loss: 0.4666
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4395 - val_accuracy: 0.8182 - val_loss: 0.4667
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4385 - val_accuracy: 0.8182 - val_loss: 0.4670
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4382 - val_accuracy: 0.8182 - val_loss: 0.4660
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4379 - val_accuracy: 0.8117 - val_loss: 0.4656
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4373 - val_accuracy: 0.8182 - val_loss: 0.4646
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4371 - val_accuracy: 0.8182 - val_loss: 0.4645
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4366 - val_accuracy: 0.8182 - val_loss: 0.4644
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4358 - val_accuracy: 0.8117 - val_loss: 0.4643
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4359 - val_accuracy: 0.8117 - val_loss: 0.4633
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4353 - val_accuracy: 0.8052 - val_loss: 0.4631
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4349 - val_accuracy: 0.8117 - val_loss: 0.4632
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4343 - val_accuracy: 0.8052 - val_loss: 0.4629
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4334 - val_accuracy: 0.8117 - val_loss: 0.4652
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4328 - val_accuracy: 0.8052 - val_loss: 0.4646
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4328 - val_accuracy: 0.8117 - val_loss: 0.4644
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4319 - val_accuracy: 0.8117 - val_loss: 0.4635
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4316 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4311 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4308 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4303 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4302 - val_accuracy: 0.8182 - val_loss: 0.4619
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.8182 - val_loss: 0.4615
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4294 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4290 - val_accuracy: 0.8117 - val_loss: 0.4620
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4285 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4280 - val_accuracy: 0.8117 - val_loss: 0.4621
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4636
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4265 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4269 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4261 - val_accuracy: 0.8052 - val_loss: 0.4635
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4254 - val_accuracy: 0.8052 - val_loss: 0.4643
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4630
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4249 - val_accuracy: 0.8052 - val_loss: 0.4630
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4239 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4235 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4230 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4623
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4223 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4214 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4215 - val_accuracy: 0.8052 - val_loss: 0.4613
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4212 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4611
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4196 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4194 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4196 - val_accuracy: 0.8052 - val_loss: 0.4621
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4192 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4190 - val_accuracy: 0.8052 - val_loss: 0.4613
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4182 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4181 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4182 - val_accuracy: 0.8052 - val_loss: 0.4610

In [29]:
# no. of nodes in a layer

def build_model2(hp):
  model = Sequential()
  units = hp.Int('units', min_value = 8, max_value = 128,step=8)
  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer="Adam", loss='binary_crossentropy', metrics=['accuracy'])


  return model

In [30]:
tuner = kt.RandomSearch(build_model2, objective= 'val_accuracy', max_trials=5, directory = 'mydir')

In [ ]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

In [ ]:
model1 = tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(x_test, y_test))

In [ ]:
def build_model3(hp):
  model3 = Sequential()
  model3.add(Dense(32, activation='relu', input_dim=8))
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model3.add(Dense(32, activation='relu'))

  model3.add(Dense(1, activation='sigmoid'))

  model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model3

In [ ]:
tuner = kt.RandomSearch(build_model3, objective='val_accuracy', max_trials=3, directory='mydir', project_name='myProject')

In [ ]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(x_train, y_train, epochs=100, initial_epoch=6, validation_data=(x_test, y_test))

In [ ]:
#how to select approptiate aoptimizer
# no. of nodes in a layer
# how to select no. of layers
# all in all one model

def build_model4(hp):
  model4 = Sequential()

  units = hp.Int('units', min_value = 8, max_value = 128,step=8)
  model4.add(Dense(units=units, activation='relu', input_dim=8))
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model4.add(Dense(32, activation='relu'))
  model4.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  model4.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model4

In [ ]:
def build_model5(hp):
  model5 = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter ==0:
      model5.add(Dense(hp.Int(' units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation', values=['relu', 'sigmoid', 'tanh']), input_dim=8))
      model5.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 ])))
    else:
      model5.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation', values=['relu', 'sigmoid', 'tanh'])))
      model5.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 ])))
    counter+=1

  model5.add(Dense(1, activation='sigmoid'))

  model5.compile(optimizer=hp.Choice('optimizer', values = ['adam', 'rmsprop', 'sgd', 'nadam', 'adadelta']),
                 loss='binary_crossentropy',
                 metrics=['accuracy'])
  return model5

In [ ]:
tuner = kt.RandomSearch(build_model5, objective='val_accuracy', max_trials=3, directory='my_project_dir1', project_name="final1")

In [ ]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(x_train, y_train, epochs=200, initial_epoch=6, validation_data=(x_test, y_test))